### ISSUE TITLE
Fix /new page

### ISSUE THREAD

**Issue by pinpox** [gchecker/gchecker#10]
https://gchecker.de/new is currently broken, no data can be entered or new checkers created.

**Comment by manuliner** [comment]
can't reproduce. It ist working in my local envoiroment. Is mysql up and running?

**Comment by pinpox** [comment]
![image](https://user-images.githubusercontent.com/1719781/147756748-71a5aea2-56ea-4bb9-82ac-74d9cfd1162d.png)
On the demo instance, not local.

**Comment by manuliner** [comment]
![grafik](https://user-images.githubusercontent.com/5088151/147757335-a76edd1d-3bb1-4613-8279-7e34acebc0be.png)

**Comment by pinpox** [comment]
![image](https://user-images.githubusercontent.com/1719781/147758349-7c90eceb-cebc-4c91-a179-448ee2ca12f4.png)
Nevermind, app is being detected by adblocker. Not sure why though. Might want to look into it anyway, so people with adblockers don't have a problem.
